let COMMENT = [
  {
    id: 1,
    comment: '반갑습니다',
    username: 'feels',
    postId: 1,
    userImg: 'https://placeimg.com/400/200/sepia',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 2,
    comment: '안녕하세요',
    username: 'lee',
    postId: 2,
    userImg: 'https://placeimg.com/400/200/grayscale',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 3,
    comment: '오오오 대단한데요',
    username: 'keem',
    postId: 3,
    userImg: 'https://placeimg.com/400/200/sepia',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 4,
    comment: '어떻게하신거에요?',
    username: 'park',
    postId: 4,
    userImg: 'https://placeimg.com/400/200/any',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 5,
    comment: '신기하네요',
    username: 'son',
    postId: 5,
    userImg: 'https://placeimg.com/400/200/any/grayscale',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 6,
    comment: '나도 해봐야지',
    username: 'leem',
    postId: 6,
    userImg: 'https://placeimg.com/400/200/any/sepia',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 7,
    comment: '졸립다',
    username: 'assss',
    postId: 7,
    userImg: 'https://placeimg.com/400/200/any/grayscale',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 8,
    comment: '저도 피곤해요',
    username: 'good',
    postId: 8,
    userImg: 'https://source.unsplash.com/random/400x200',
    created_at: '12월12일',
    update_at: '12월12일',
  },
];

export default COMMENT;
