let POST = [
  {
    id: 1,
    title: '취준생에게 유용한 링크들 정리',
    contents:
      '도움되는 정보는 정말정말정말 많지만 링크를 잊어버리기도 쉽고, 내가 있는 정보만큼 활용을 하지 못하는것 같아서 한눈에 볼 수 있게 모아봤다. 도움되는 정보는 정말정말정말 많지만 링크를 잊어버리기도 쉽고, 내가 있는 정보만큼 활용을 하지 못하는것 같아서 한눈에 볼 수 있게 모아봤다.도움되는 정보는 정말정말정말 많지만 링크를 잊어버리기도 쉽고, 내가 있는 정보만큼 활용을 하지 못하는것 같아서 한눈에 볼 수 있게 모아봤다.도움되는 정보는 정말정말정말 많지만 링크를 잊어버리기도 쉽고, 내가 있는 정보만큼 활용을 하지 못하는것 같아서 한눈에 볼 수 있게 모아봤다.도움되는 정보는 정말정말정말 많지만 링크를 잊어버리기도 쉽고, 내가 있는 정보만큼 활용을 하지 못하는것 같아서 한눈에 볼 수 있게 모아봤다.도움되는 정보는 정말정말정말 많지만 링크를 잊어버리기도 쉽고, 내가 있는 정보만큼 활용을 하지 못하는것 같아서 한눈에 볼 수 있게 모아봤다.도움되는 정보는 정말정말정말 많지만 링크를 잊어버리기도 쉽고, 내가 있는 정보만큼 활용을 하지 못하는것 같아서 한눈에 볼 수 있게 모아봤다.도움되는 정보는 정말정말정말 많지만 링크를 잊어버리기도 쉽고, 내가 있는 정보만큼 활용을 하지 못하는것 같아서 한눈에 볼 수 있게 모아봤다.도움되는 정보는 정말정말정말 많지만 링크를 잊어버리기도 쉽고, 내가 있는 정보만큼 활용을 하지 못하는것 같아서 한눈에 볼 수 있게 모아봤다.도움되는 정보는 정말정말정말 많지만 링크를 잊어버리기도 쉽고, 내가 있는 정보만큼 활용을 하지 못하는것 같아서 한눈에 볼 수 있게 모아봤다.도움되는 정보는 정말정말정말 많지만 링크를 잊어버리기도 쉽고, 내가 있는 정보만큼 활용을 하지 못하는것 같아서 한눈에 볼 수 있게 모아봤다.',
    fileUrl: 'https://source.unsplash.com/random/400x200',
    userId: 1,
    comment: '20개의 댓글',
    created_at: '2020년 11월 11일',
    update_at: '2020년 11월 11일',
  },
  {
    id: 2,
    title: '자바스크립트 코드 테크닉 모음집',
    contents: '공부하면서 기록하고 싶게 했던 코드들',
    fileUrl: 'https://placeimg.com/400/200/any/grayscale',
    userId: 2,
    comment: '9개의 댓글',
    created_at: '2020년 11월 11일',
    update_at: '2020년 11월 11일',
  },
  {
    id: 3,
    title: '개발자를 위한 트렌드 2021',
    contents: '남은 2020년을 정리하면서 써본 컨텐츠',
    fileUrl: 'https://placeimg.com/400/200/any/sepia',
    userId: 3,
    comment: '1개의 댓글',
    created_at: '2020년 11월 11일',
    update_at: '2020년 11월 11일',
  },
  {
    id: 4,
    title: '질문 잘 하는 방법',
    contents: '질문은 어떻게 해야할까?',
    fileUrl: 'https://placeimg.com/400/200/any/grayscale',
    userId: 4,
    comment: '20개의 댓글',
    created_at: '2020년 11월 11일',
    update_at: '2020년 11월 11일',
  },
  {
    id: 5,
    title: '개발 입문 1달차',
    contents: '개발 입문 1달차 뭘했을까 그동안?',
    fileUrl: 'https://placeimg.com/400/200/any',
    userId: 5,
    comment: '2개의 댓글',
    created_at: '2020년 11월 11일',
    update_at: '2020년 11월 11일',
  },
  {
    id: 6,
    title: '코드스테이츠를 마치며',
    contents: '힘들지만 즐거웠던 경험',
    fileUrl: 'https://placeimg.com/400/200/sepia',
    userId: 6,
    comment: '20개의 댓글',
    created_at: '2020년 11월 11일',
    update_at: '2020년 11월 11일',
  },
  {
    id: 7,
    title: '밥은 먹고 코딩하자',
    contents: '다 먹고살자고 하는일 아닙니까!?',
    fileUrl: 'https://placeimg.com/400/200/grayscale',
    userId: 7,
    comment: '5개의 댓글',
    created_at: '2020년 11월 11일',
    update_at: '2020년 11월 11일',
  },
  {
    id: 8,
    title: '좋은 코드? 그게뭐에요?',
    contents:
      '개발자에게 좋은 코드라는 건 무엇일까? 알다가도 모르겠는 좋은코드, 함께 알아보자 ',
    fileUrl: 'https://placeimg.com/400/200/sepia',
    userId: 8,
    comment: '6개의 댓글',
    created_at: '2020년 11월 11일',
    update_at: '2020년 11월 11일',
  },
];

export default POST;
