let USER = [
  {
    id: 1,
    username: 'feels',
    email: 'feels@gmail.com',
    password: 1234,
    userImg: 'https://placeimg.com/400/200/sepia',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 2,
    username: 'lee',
    email: 'feels@gmail.com',
    password: 1234,
    userImg: 'https://placeimg.com/400/200/grayscale',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 3,
    username: 'keem',
    email: 'feels@gmail.com',
    password: 1234,
    userImg: 'https://placeimg.com/400/200/sepia',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 4,
    username: 'park',
    email: 'feels@gmail.com',
    password: 1234,
    userImg: 'https://placeimg.com/400/200/any',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 5,
    username: 'son',
    email: 'feels@gmail.com',
    password: 1234,
    userImg: 'https://placeimg.com/400/200/any/grayscale',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 6,
    username: 'leem',
    email: 'feels@gmail.com',
    password: 1234,
    userImg: 'https://placeimg.com/400/200/any/sepia',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 7,
    username: 'assss',
    email: 'feels@gmail.com',
    password: 1234,
    userImg: 'https://placeimg.com/400/200/any/grayscale',
    created_at: '12월12일',
    update_at: '12월12일',
  },
  {
    id: 8,
    username: 'good',
    email: 'feels@gmail.com',
    password: 1234,
    userImg: 'https://source.unsplash.com/random/400x200',
    created_at: '12월12일',
    update_at: '12월12일',
  },
];

export default USER;
